services:

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: gabrielskf/node
    container_name: app
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gabrielskf/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge
